language: node_js
node_js:
  - "10"
before_script:
  - npm run format
  - npm run lint
  - npm run build
after_success:
  - npm run coveralls
  - npm run docs
before_deploy:
  - tar -zcf dist.tar.gz dist
  - tar -zcf docs.tar.gz docs
  - tar -zcf coverage.tar.gz coverage
deploy:
  - provider: releases
    api_key: $DEPLOYMENT_KEY
    file_glob: true
    file: /*.tar.gz
    skip_cleanup: true
    draft: true
    on:
      tags: true

  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $DEPLOYMENT_KEY
    on:
      tags: true
